# Generated by Django 5.1.5 on 2025-02-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_alter_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='Dark Mode'),
        ),
    ]
