# Generated by Django 4.2.17 on 2025-01-16 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(default='ff02cbc6-f5b1-49c3-b7f2-500252cb0ad8', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='cotizador.company'),
        ),
    ]
